### ISSUE TITLE
Which fork is the one to use?

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#35]
Hi,

I've based our fork on the original repository. But in trying to get it working I discovered that there are several bugfixes in e.g. https://github.com/earth2observe-pml/GISportal 

Should we rather use https://github.com/earth2observe-pml/GISportal ? If so then this should be made clear in the README of the original repository.

**Comment by bcalton** [comment]
Christoph,

We have been making some considerable progress with the GISportal over the past few months and the version hosted here has become significantly out of date. Around November last year we also made the decision to use an internally hosted version of Gitlab for our version control software rather than Github. This has made the repository appear a bit inactive recently but this is not the case.

We are due to release a major update this week as we come to the end of a project that is using the portal. If you are able to wait for a few days we will be pushing the latest version to Github; the project ends this coming Friday so it really will be in the next couple of days. In the meantime, if you have an instance of Docker running you could download a pre-built container image directly from the Docker Hub; the GISportal can be found at https://hub.docker.com/r/pmlrsg/gisportal/ This will give you an instance that contains all the recent developments and new features without the worry of having to install everything. 

I will let you know once we have pushed the latest code to Github, and this is what you should use (with an updated readme) as this will supersede the earth2observe fork. 

Cheers,
Ben

**Comment by cpaulik** [comment]
Thanks, this is great news. 

I'll try the docker container tomorrow and look forward to the latest version.

**Comment by bcalton** [comment]
@cpaulik,
Just to let you know that the master branch has been updated with the latest version of the code. If you have any questions or need help with anything please let me know.

Cheers,
Ben
