### ISSUE TITLE
submodules reference https://gitlab.rsg.pml.ac.uk

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#38]
This is a problem also in the plotting repo.

**Comment by bcalton** [comment]
This is due to the way the repository is setup. We use Gitlab internally and have this setup to push to Github automcatically, however, I hadn't fully appreciated the issue this would cause with the submodules. For now the way to get around it is to edit the .gitmodules file in the root of the repository and change the URL for the plotting submodule to https://github.com/pmlrsg/plotting

You will have to do the same in the plotting submodule to alter the URL for the data_extractor submodule, changing this to https://github.com/pmlrsg/data_extractor

I will work on a long term solution, probably involving moving away from submodules, and let you know when this is available. 

Cheers,
Ben

**Comment by bcalton** [comment]
The plotting submodule has been flattened into this repository to avoid broken references

**Comment by bcalton** [comment]
Christoph,

I have updated the master branch with a number of updates, including the
reordering of the Dockerfile which you committed to your fork. This
makes good sense, so thank you for this, and for spotting/reporting the
jimp version bug.

I have updated the container on the Docker Hub as well, so these changes
are reflected there too.

I would be curious to know how you are getting on with it. So, if you
have a couple of minutes perhaps you could let me know how you are using
it and what your thoughts are about it. Many thanks.

Kind regards,

Ben


On 22/03/16 11:35, Christoph Paulik wrote:
> This is a problem also in the plotting repo.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pmlrsg/GISportal/issues/38>
> 


Please visit our new website at www.pml.ac.uk and follow us on Twitter @PlymouthMarine

Winner of the Environment & Conservation category, the Charity Awards 2014.

Plymouth Marine Laboratory (PML) is a company limited by guarantee registered in England & Wales, company number 4178503. Registered Charity No. 1091222. Registered Office: Prospect Place, The Hoe, Plymouth  PL1 3DH, UK. 

This message is private and confidential. If you have received this message in error, please notify the sender and remove it from your system. You are reminded that e-mail communications are not secure and may contain viruses; PML accepts no liability for any loss or damage which may be caused by viruses.

**Comment by cpaulik** [comment]
Hi Ben,

Thanks for the updates. I was going to submit pull requests for 
the changes I made but am glad that you included them already now.

I've been playing with the GISportal on and off for the last weeks 
and we have a test version of it running since Wednesday for the 
CCI soil moisture data viewer. You can check it out at 
http://geo.tuwien.ac.at/cci_dataviewer/  Generally we are quite 
happy with the GISportal. One area that I would like to work on a 
little bit is the plotting part. What would you think about making 
a stand-alone Python package out of the plotting/data_extractor 
part of the repository? This would enable us and others to use the 
functionality in other programs. I could already see some uses for 
it in other projects.

A more direct issue that I want to look into is the time 
estimation of plots since they are way off if the netCDF file 
behind the WCS server is chunked e.g. for time series access. 
Which is something we do for the CCI data. But this might not be 
solvable without the user providing some metadata about the 
chunking. 

Thanks again and have a nice weekend,
Christoph 


 

Ben Calton writes:

> Christoph,
>
> I have updated the master branch with a number of updates, 
> including the reordering of the Dockerfile which you committed 
> to your fork. This makes good sense, so thank you for this, and 
> for spotting/reporting the jimp version bug.
>
> I have updated the container on the Docker Hub as well, so these 
> changes are reflected there too.
>
> I would be curious to know how you are getting on with it. So, 
> if you have a couple of minutes perhaps you could let me know 
> how you are using it and what your thoughts are about it. Many 
> thanks.
>
> Kind regards,
>
> Ben
>
>
> On 22/03/16 11:35, Christoph Paulik wrote:
>> This is a problem also in the plotting repo.
>> 
>> — You are receiving this because you are subscribed to this 
>> thread.  Reply to this email directly or view it on GitHub 
>> <https://github.com/pmlrsg/GISportal/issues/38>
>> 
>
>
> Please visit our new website at www.pml.ac.uk and follow us on 
> Twitter @PlymouthMarine
>
> Winner of the Environment & Conservation category, the Charity 
> Awards 2014.
>
> Plymouth Marine Laboratory (PML) is a company limited by 
> guarantee registered in England & Wales, company number 4178503. 
> Registered Charity No. 1091222. Registered Office: Prospect 
> Place, The Hoe, Plymouth  PL1 3DH, UK. 
>
> This message is private and confidential. If you have received 
> this message in error, please notify the sender and remove it 
> from your system. You are reminded that e-mail communications 
> are not secure and may contain viruses; PML accepts no liability 
> for any loss or damage which may be caused by viruses.
>
>
>
> --- You are receiving this because you authored the thread. 
> Reply to this email directly or view it on GitHub: 
> https://github.com/pmlrsg/GISportal/issues/38#issuecomment-215732487


-- 

-------------------------------------------------------
Christoph Paulik
Twitter, Github: @cpaulik
PGP: 8CFC D7DF 2867 B2DC 749B  1B0A 6E3B A262 5186 A0AC
