### ISSUE TITLE
Being logged in on one GISportal seems to break other GISportal

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#43]
I'm currently testing the user dashboard and noticed that http://rs.geo.tuwien.ac.at/data_viewer/cci-nrt/ breaks as soon as I log myself in at http://rs.geo.tuwien.ac.at/data_viewer/ascat/

**Comment by ojsdude** [comment]
Does the instance at: http://rs.geo.tuwien.ac.at/data_viewer/cci-nrt/ have OAuth set up?

**Comment by ojsdude** [comment]
I would have to do some further digging another day, but it seems the user.js file is getting a user as being logged in because it is saved from the other page. This means it is sending this information to the server when `get_cache` is called. We will need to look at making sure that a user is only logged in if the portal allows for logging in

**Comment by cpaulik** [comment]
http://rs.geo.tuwien.ac.at/data_viewer/cci-nrt/ does not have oauth setup.

**Comment by ojsdude** [comment]
Could you try patching with 98e873adba402a184ee632a5ad3706556210ff02 and see what it does?

**Comment by cpaulik** [comment]
The patch fixes the issue.
