### ISSUE TITLE
.install.sh not creating server config in ./GISportal/config/site-settings/<server name>

### ISSUE THREAD

**Issue by iMarang** [pmlrsg/GISportal#49]
Hi,

I'm setting up GISportal on a virtual machine (RHEL 6.8).  This vm is only available within the university domain and so I've gone for 'no' to ssl and authentication options as a test.

I've gotten everything installed and running up to the point of launching node app.js

When I've run the ./install.sh it goes through the install process smoothly with no errors but 4 warnings:

WARN: Dropping unused variable csv_found [GISportal.js:6134,10]
WARN: Dropping side-effect-free statement [GISportal.js:11555,9]
WARN: Dropping side-effect-free statement [GISportal.js:19587,6]
WARN: Dropping side-effect-free statement [GISportal.js:21336,3]

And says it completes with no errors.  However, when I launch node.js these are the messages I see:
"
No server config was found.

If this is a new installation you should run ./install.sh to create a configuration for your domain.

List of domains with Google authentication settings:

(node:38304) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

GISportal server listening on port 6789
Connected to redis.
Redis client ready.
"
I check on a browser by going to the vm hostname\domain name from ./install.sh and port 6789 but get 'site can't be reached'.  I notice there's a) no server config found, b) list of google auth is empty and c) deprecation warning.  When I check the "./GISportal/config/site-settings/<domain name>" dir it's empty.

I'm not a linux/redis/node guru obviously, can you please advise what might be causing these issues?

Cheers
Ian

**Comment by bcalton** [comment]
Hi Ian,

All looks like it should work. The warnings can safely be ignored (we really should remove the chunks of code they refer to). The fact that there is no server config should not necessarily be a problem either; `config/global-config-server.js` contains the minimum required to get the application running. As you selected `no` to the SSL and authentication questions in the install script I would expect the 'List of domains with Google authentication settings:' to be empty. 

I would expect the install script to create a folder using the domain name that you supplied, however, the application will make new directories on-the-fly when the application is accessed via a new domain name. 

The fact that you are seeing this:
```
GISportal server listening on port 6789
Connected to redis.
Redis client ready.
```
tells me that the application is running and should be accessible. There are a couple of potential causes of why you cannot access it, but first I'd like to make sure that it's behaving properly.

Make sure the application is running (`node app.js`), then please run this curl command in a new tab *on the VM* to make a request:
```
curl -o /tmp/index.html http://localhost:6789
```
If the file that has downloaded (`/tmp/index.html`) is very similar to the source file in `src/index.html` then this shows that the app is running properly, but you cannot get to it from your machine. If it's not please post the contents here so that I can understand what's going on. Incidentally, there should also now be a new folder in `config/site-settings/localhost:6789`

If the index files are similar the application is working. In which case, things to look at:
- Firewall enabled on the VM; if this is on please try switching it off briefly to eliminate this
- SELinux is enabled? run `getenforce` to get the status of SELinux currently and if you get an answer of 'Enforcing' try turning this off temporarily too

Please let me know if any of this helps

Regards,
Ben

**Comment by iMarang** [comment]
Hi Ben,

Thank you for your prompt response!

OK, I've run the curl command you gave.  The '/tmp/index.html' and
'/src/index.html' are identical.  I checked SELinux and it shows
'Permissive' as the status. I've gone back to my university's server team
to confirm on the status of the firewall, but I had another question int he
meantime.

What exactly is the domain name I should be entering in the browser to
access the portal?  I just want to confirm that this should be exactly what
has been specified in the ./install.sh run.

Cheers
Ian

**Comment by iMarang** [comment]
Hi again Ben,

Actually, sorted out the problem.  Turns out it was as simple as our IT had
locked down the machine so hard that only port 22 was accessible
*facepalm*. netstat and other commands showed port 6789 as listening, but
it required IT omniscience to see and fix it.

Loaded up and looks great, now for the fun stuff of loading up some
datasets...

Thanks for the software and your help.
Ian

**Comment by bcalton** [comment]
Ian,

Glad to hear you got it sorted. Please let me know if there's anything else that we can help with.

Cheers,
Ben
